// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Fa4mXU0zR-Y3Mc3y2v-1u9X8V0OWIJ8',
    appId: '1:300805243904:web:bb414c4f9070cf850504e5',
    messagingSenderId: '300805243904',
    projectId: 'tapscore-235cc',
    authDomain: 'tapscore-235cc.firebaseapp.com',
    storageBucket: 'tapscore-235cc.firebasestorage.app',
    measurementId: 'G-R775ZGP92H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-_xT16Vb0jl0KO68MoEQG_eDsVbPb1lg',
    appId: '1:300805243904:android:e29e59c953b0676a0504e5',
    messagingSenderId: '300805243904',
    projectId: 'tapscore-235cc',
    storageBucket: 'tapscore-235cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsN1k-ntTa37R6fdOmD678N6WL_G7pUq4',
    appId: '1:300805243904:ios:7288d54e1d517f1a0504e5',
    messagingSenderId: '300805243904',
    projectId: 'tapscore-235cc',
    storageBucket: 'tapscore-235cc.firebasestorage.app',
    iosBundleId: 'com.lbin.tapscore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsN1k-ntTa37R6fdOmD678N6WL_G7pUq4',
    appId: '1:300805243904:ios:d8ba51bd1ef2c1680504e5',
    messagingSenderId: '300805243904',
    projectId: 'tapscore-235cc',
    storageBucket: 'tapscore-235cc.firebasestorage.app',
    iosBundleId: 'com.example.tapScore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Fa4mXU0zR-Y3Mc3y2v-1u9X8V0OWIJ8',
    appId: '1:300805243904:web:63279ec327ab9b2d0504e5',
    messagingSenderId: '300805243904',
    projectId: 'tapscore-235cc',
    authDomain: 'tapscore-235cc.firebaseapp.com',
    storageBucket: 'tapscore-235cc.firebasestorage.app',
    measurementId: 'G-SVEDRJJZP0',
  );
}
