jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - name: Build iOS
        env:
          AD_UNIT_ID: ${{ secrets.AD_UNIT_ID }}
          AD_APP_ID: ${{ secrets.AD_APP_ID }}
        run: flutter build ios --release --dart-define=AD_UNIT_ID=$AD_UNIT_ID --dart-define=AD_APP_ID=$AD_APP_ID 